# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1122, 872)
        self.camera = QtWidgets.QPushButton(Dialog)
        self.camera.setGeometry(QtCore.QRect(10, 40, 111, 41))
        self.camera.setObjectName("camera")
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(10, 100, 111, 41))
        self.exit.setObjectName("exit")
        self.master = QtWidgets.QLabel(Dialog)
        self.master.setGeometry(QtCore.QRect(140, 40, 451, 257))
        self.master.setObjectName("master")
        self.sub1 = QtWidgets.QLabel(Dialog)
        self.sub1.setGeometry(QtCore.QRect(620, 40, 451, 257))
        self.sub1.setObjectName("sub1")
        self.sub2 = QtWidgets.QLabel(Dialog)
        self.sub2.setGeometry(QtCore.QRect(140, 340, 451, 257))
        self.sub2.setObjectName("sub2")
        self.BP = QtWidgets.QLabel(Dialog)
        self.BP.setGeometry(QtCore.QRect(620, 340, 451, 257))
        self.BP.setObjectName("BP")

        self.retranslateUi(Dialog)
        self.camera.clicked.connect(Dialog.runCamera)
        self.exit.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.camera.setText(_translate("Dialog", "开启摄像头"))
        self.exit.setText(_translate("Dialog", "退出"))
        self.master.setText(_translate("Dialog", "master camera"))
        self.sub1.setText(_translate("Dialog", "sub1 camera"))
        self.sub2.setText(_translate("Dialog", "sub2 camera"))
        self.BP.setText(_translate("Dialog", "BP estimation"))
